const SAVE_KEY='anoria-save-v1';
const state={screen:'title',level:1,chapter:1,location:'Whispering Vale',hp:100,maxHp:100,mana:40,gold:25,shards:0,xp:0,inventory:['Moonleaf Potion'],weapon:'Dawnblade',choices:[],sound:true,paused:false};
const locations=[
 {name:'Whispering Vale',chapter:1,desc:'A silver forest where forgotten voices guide the brave.',quest:'The First Shard',detail:'Follow the blue fireflies into the ancient vale.'},
 {name:'Emberfall Village',chapter:1,desc:'A lantern-lit refuge threatened by shadow wolves.',quest:'Ashes and Oaths',detail:'Defend the village and find the old keeper.'},
 {name:'Sunken Ruins',chapter:2,desc:'A drowned temple hiding the second Dawn Shard.',quest:'Beneath Still Water',detail:'Solve the moon-gate and descend below the ruins.'},
 {name:'Frostspire Pass',chapter:3,desc:'A frozen mountain path guarded by an ancient warden.',quest:'The Silent Giant',detail:'Cross the pass and earn the warden’s trust.'},
 {name:'Obsidian Citadel',chapter:4,desc:'The enemy fortress beyond the edge of the world.',quest:'The Last Dawn',detail:'Face the Night King and restore the sky.'}
];
const chars={aria:{name:'ARIA',role:'Dawnblade',icon:'⚔️',bio:'A young ranger carrying a blade forged from the first sunrise.',color:'#e8c77a'},lyra:{name:'LYRA',role:'Starweaver',icon:'🔮',bio:'A mysterious mage who can hear the memories inside crystals.',color:'#9f8cff'},torren:{name:'TORREN',role:'Stoneguard',icon:'🛡️',bio:'A wandering guardian with an unbreakable oath.',color:'#8bb9c8'},nyx:{name:'NYX',role:'Shadow Scout',icon:'🦊',bio:'A clever scout who knows every secret road in Anoria.',color:'#c18cff'},king:{name:'THE NIGHT KING',role:'Final Enemy',icon:'👑',bio:'The ruler who stole the Dawn Shards to freeze time.',color:'#a36cff'}};
const scenes={
  1:{intro:[['LYRA','The stars are falling again. The first shard has awakened beneath this forest.'],['ARIA','Then I’ll find it before the darkness does.'],['LYRA','Follow the blue lights. But remember: Anoria tests the heart before the sword.']],choices:[{text:'Follow the fireflies',next:'combat'},{text:'Search the old shrine',next:'shrine'}]},
  2:{intro:[['TORREN','You came at the right hour. The village gates will not survive another night.'],['ARIA','Who is attacking?'],['TORREN','Things without names. They fear the Dawn Shard.']],choices:[{text:'Defend the gate',next:'combat'},{text:'Question the keeper',next:'keeper'}]},
  3:{intro:[['LYRA','The temple is below us. The water remembers everyone who entered.'],['ARIA','And if the gate refuses us?'],['LYRA','Give it a memory worth keeping.']],choices:[{text:'Enter the moon-gate',next:'ruins'},{text:'Study the inscription',next:'inscription'}]},
  4:{intro:[['TORREN','The pass ends at the warden’s throne. No traveler has crossed it in a century.'],['ARIA','Then we’ll become the first.']],choices:[{text:'Challenge the warden',next:'combat'},{text:'Offer the shard',next:'warden'}]},
  5:{intro:[['KING','You gathered every shard only to deliver them to me.'],['ARIA','No. I gathered them so the world could take back its dawn.'],['KING','Then let the final chapter begin.']],choices:[{text:'Face the Night King',next:'boss'},{text:'Call on your allies',next:'allies'}]}
};
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
function save(){localStorage.setItem(SAVE_KEY,JSON.stringify(state)); updateContinue()}
function load(){const s=localStorage.getItem(SAVE_KEY);if(s){Object.assign(state,JSON.parse(s));showGame();renderLevel();}}
function updateContinue(){$('#continue-btn').classList.toggle('hidden',!localStorage.getItem(SAVE_KEY))}
function show(id){$$('.screen').forEach(x=>x.classList.remove('active'));$(id).classList.add('active')}
function showGame(){show('#game-screen');state.screen='game';}
function renderLevel(){const l=locations[state.level-1];state.location=l.name;$('#chapter-label').textContent=`Chapter ${l.chapter}`;$('#location-label').textContent=l.name;$('#location-banner').textContent=l.name.toUpperCase();$('#quest-title').textContent=l.quest;$('#quest-text').textContent=l.detail;$('#scene-art').textContent=state.level===5?'♛':state.level===4?'🗿':state.level===3?'🏛️':state.level===2?'🏘️':'♞';$('#scene-art').style.fontSize='120px';updateHud();}
function updateHud(){$('#quest-type').textContent=state.level===5?'FINAL QUEST':'MAIN QUEST'}
function dialogue(lines,done){let i=0;$('#dialogue').classList.remove('hidden');const render=()=>{$('#speaker').textContent=lines[i][0];$('#dialogue-text').textContent=lines[i][1]};render();$('#dialogue-next').onclick=()=>{i++;if(i>=lines.length){$('#dialogue').classList.add('hidden');if(done)done();}else render()};}
function choices(arr){const p=$('#choice-panel');p.innerHTML='';p.classList.remove('hidden');arr.forEach(c=>{const b=document.createElement('button');b.textContent=c.text;b.onclick=()=>{p.classList.add('hidden');handleChoice(c.next)};p.appendChild(b)})}
function startLevel(){const s=scenes[state.level].intro;dialogue(s,()=>choices(s.choices))}
function handleChoice(next){if(next==='combat'||next==='boss')return combat(next==='boss'); if(next==='shrine')return reward('Moon Shrine','You discover a hidden Dawn Shard beneath the roots.',20,1);if(next==='keeper')return dialogue([['KEEPER','The second shard is not a thing. It is an oath.'],['ARIA','Then I swear to protect this village.']],()=>reward('Keeper’s Oath','The village gives you an ancient charm.',30,0));if(next==='ruins')return reward('Sunken Gate','The moon-gate opens and reveals a Dawn Shard.',40,1);if(next==='inscription')return dialogue([['LYRA','The symbols say: only a shared memory opens the way.'],['ARIA','Take mine: the day I first saw the stars.']],()=>reward('Memory Gate','The temple recognizes your courage.',35,1));if(next==='warden')return reward('Warden’s Trust','The giant bows and reveals a Dawn Shard.',50,1);if(next==='allies')return dialogue([['LYRA','Stars answer.'],['TORREN','Stone answers.'],['NYX','And shadows answer.'],['ARIA','Together, then.']],()=>combat(true));}
function reward(title,text,xp,shard){state.xp+=xp;state.shards+=shard;state.gold+=Math.ceil(xp/5);save();dialogue([[title,text],["ARIA",`The journey continues. (+${xp} XP${shard?', +1 Dawn Shard':''})`]],()=>advance())}
function combat(boss=false){let enemy=boss?{name:'NIGHT KING',hp:150,max:150,power:22}:{name:'SHADOW BEAST',hp:65,max:65,power:13};let rounds=0;const fight=()=>{const damage=18+Math.floor(Math.random()*14);enemy.hp-=damage;state.hp=Math.max(1,state.hp-(enemy.hp>0?enemy.power:0));rounds++;if(enemy.hp<=0){state.xp+=boss?100:35;state.shards+=boss?1:0;save();dialogue([[enemy.name,'Your dawn… is stronger than my night.'],['ARIA',boss?'The sky belongs to everyone.':'The vale is safe—for now.']],()=>boss?ending():advance());return}dialogue([[enemy.name,`A dark strike tears through the air. Enemy HP: ${Math.max(0,enemy.hp)}.`],["ARIA",`Dawnblade! Damage ${damage}. My HP: ${state.hp}.`]],()=>{if(state.hp<=1){state.hp=100;dialogue([['LYRA','The shard pulled you back from the edge. Rest, hero.']],()=>fight());}else fight()})};fight()}
function advance(){if(state.level<locations.length){state.level++;state.chapter=locations[state.level-1].chapter;state.hp=Math.min(state.maxHp,state.hp+25);save();renderLevel();setTimeout(startLevel,300)}else ending()}
function ending(){state.level=5;save();$('#quest-title').textContent='ANORIA RESTORED';$('#quest-text').textContent='You restored the Dawn. A new age begins.';dialogue([['LYRA','Look. The stars are moving again.'],['ARIA','Then our story is not over.'],['NARRATOR','ANORIA — Chapter One Complete.']],()=>openModal(`<h2>🌅 Dawn Restored</h2><p>You completed the first 2026 adventure chapter.</p><p><b>XP:</b> ${state.xp} &nbsp; <b>Gold:</b> ${state.gold} &nbsp; <b>Shards:</b> ${state.shards}</p><button class="primary" onclick="closeModal()">Return to Anoria</button>`))}
function openModal(html){$('#modal-content').innerHTML=html;$('#overlay').classList.remove('hidden')}function closeModal(){$('#overlay').classList.add('hidden')}
function inventory(){openModal(`<h2>🎒 Inventory</h2><div class="inventory-grid">${state.inventory.map(i=>`<div class="item">✨<br>${i}</div>`).join('')}<div class="item">⚔️<br>${state.weapon}</div><div class="item">💎<br>${state.shards} Dawn Shards</div><div class="item">🪙<br>${state.gold} Gold</div><div class="item">⭐<br>${state.xp} XP</div></div>`)}
function map(){openModal(`<h2>🗺 Map of Anoria</h2><div class="map">${locations.map((l,i)=>`<div class="${i===state.level-1?'current':''}"><b>${i+1}. ${l.name}</b><br><small>Chapter ${l.chapter}</small></div>`).join('')}</div>`)}
function journal(){openModal(`<h2>📖 Journal</h2><p><b>The Prophecy:</b> When the Dawn Shards reunite, the frozen sky will breathe again.</p><p><b>Current quest:</b> ${locations[state.level-1].quest}</p><p><b>Companions:</b> Lyra, Torren, Nyx.</p><p><b>Progress:</b> ${state.shards}/5 shards.</p>`)}
let audioCtx;function beep(freq=440,dur=.12,type='sine'){if(!state.sound)return;audioCtx??=new (window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(.04,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+dur);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+dur)}
function how(){openModal('<h2>How to Play</h2><p>Explore each location, choose dialogue paths, defeat shadow creatures, collect Dawn Shards and protect Anoria.</p><ul><li>✦ Interact starts the current story event.</li><li>🎒 Inventory shows gear, gold and shards.</li><li>🗺 Map shows your journey.</li><li>Use the arrow controls to trigger exploration sounds.</li><li>Your progress saves automatically.</li></ul>')}
$('#start-btn').onclick=()=>{Object.assign(state,{level:1,chapter:1,hp:100,mana:40,gold:25,shards:0,xp:0,inventory:['Moonleaf Potion'],choices:[]});showGame();renderLevel();save();beep(660,.2);startLevel()};$('#continue-btn').onclick=()=>{load();beep(520,.1)};$('#how-btn').onclick=how;$('#close-modal').onclick=closeModal;$('#overlay').onclick=e=>{if(e.target.id==='overlay')closeModal()};$('#inventory-btn').onclick=()=>{inventory();beep(300)};$('#map-btn').onclick=()=>{map();beep(350)};$('#journal-btn').onclick=()=>{journal();beep(420)};$('#interact-btn').onclick=()=>{startLevel();beep(660)};$('#sound-btn').onclick=()=>{state.sound=!state.sound;$('#sound-btn').textContent=state.sound?'🔊':'🔇';beep(500)};$('#pause-btn').onclick=()=>{state.paused=!state.paused;openModal(`<h2>${state.paused?'⏸ Paused':'▶ Resumed'}</h2><p>${state.paused?'Your journey is safe. Close this window to continue.':'Welcome back to Anoria.'}</p>`) };
$$('[data-move]').forEach(b=>b.onclick=()=>{beep(180+Math.random()*100,.07,'triangle');$('#scene-art').animate([{transform:'translateX(-50%) translateY(0)'},{transform:'translateX(-50%) translateY(-5px)'},{transform:'translateX(-50%) translateY(0)'}],220)});
document.addEventListener('keydown',e=>{if(e.key==='Enter'){$('#interact-btn').click()}if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key)){beep(220,.06,'triangle')}});updateContinue();
