const SAVE_KEY='anoria-save-v2', SETTINGS_KEY='anoria-settings-v1';
const state={screen:'title',level:1,hp:100,maxHp:100,mana:60,maxMana:60,gold:80,xp:0,shards:0,inventory:['Moonleaf Potion','Dawn Fragment'],weapon:'Dawnblade',abilities:['slash','arcane','guard','heal'],sound:true,music:true,volume:.45,paused:false,guard:false,questDone:0,combat:false,enemy:null,position:{x:50,y:70}};
const locations=[
{name:'Whispering Vale',chapter:1,quest:'The First Shard',detail:'Find the blue fireflies and awaken the Moon Shrine.',type:'forest',npc:['Lyra'],enemy:'Shadow Beast'},
{name:'Emberfall Village',chapter:1,quest:'Ashes and Oaths',detail:'Protect the village and earn Torren’s oath.',type:'village',npc:['Torren'],enemy:'Ash Wolf'},
{name:'Sunken Ruins',chapter:2,quest:'Beneath Still Water',detail:'Open the moon-gate and recover the second shard.',type:'ruins',npc:['Lyra'],enemy:'Drowned Wraith'},
{name:'Frostspire Pass',chapter:3,quest:'The Silent Giant',detail:'Defeat the ice warden or prove your courage.',type:'frost',npc:['Torren','Nyx'],enemy:'Frost Warden'},
{name:'Obsidian Citadel',chapter:4,quest:'The Last Dawn',detail:'Break the Night King’s three phases and restore the sky.',type:'citadel',npc:['Lyra','Torren','Nyx'],enemy:'Night King'}];
const npcs={Lyra:{role:'Starweaver',icon:'🔮',color:'#9f8cff',bio:'A star mage who reads memories hidden in crystals.'},Torren:{role:'Stoneguard',icon:'🛡️',color:'#8bb9c8',bio:'A guardian sworn to protect the weak.'},Nyx:{role:'Shadow Scout',icon:'🦊',color:'#c18cff',bio:'A scout who can walk unseen between worlds.'}};
const weapons={Dawnblade:{power:18,rarity:'Legendary',ability:'Solar Arc'},Moonbow:{power:14,rarity:'Rare',ability:'Moon Shot'},Starstaff:{power:12,rarity:'Epic',ability:'Astral Burst'}};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function save(){localStorage.setItem(SAVE_KEY,JSON.stringify(state));updateContinue()};function load(){const s=localStorage.getItem(SAVE_KEY);if(s){Object.assign(state,JSON.parse(s));showGame();renderLevel()}}function updateContinue(){$('#continue-btn').classList.toggle('hidden',!localStorage.getItem(SAVE_KEY))}
function show(id){$$('.screen').forEach(x=>x.classList.remove('active'));$(id).classList.add('active')}function showGame(){show('#game-screen');state.screen='game'}
function renderLevel(){const l=locations[state.level-1];$('#chapter-label').textContent=`Chapter ${l.chapter}`;$('#location-label').textContent=l.name;$('#location-banner').textContent=l.name.toUpperCase();$('#quest-title').textContent=l.quest;$('#quest-text').textContent=l.detail;$('#quest-progress').style.width=Math.min(100,state.questDone*20)+'%';$('#quest-type').textContent=state.level===5?'FINAL QUEST':'MAIN QUEST';sceneTheme(l.type);renderNPCs(l.npc);updateHud();state.position={x:50,y:70};movePlayer(0,0);}
function sceneTheme(type){const s=$('#scene');s.dataset.theme=type;$('#enemy').classList.add('hidden');$('#combat-hud').classList.add('hidden');state.combat=false;burst(16)}
function renderNPCs(names){const wrap=$('#npcs');wrap.innerHTML='';names.forEach((n,i)=>{const e=document.createElement('div');e.className='npc';e.style.left=(18+i*28)+'%';e.style.bottom=(18+i%2*5)+'%';e.innerHTML=`<b>${npcs[n].icon}</b><small>${n}</small>`;e.onclick=()=>talk(n);wrap.appendChild(e)})}
function updateHud(){$('#hp').textContent=state.hp;$('#mana').textContent=state.mana;$('#gold').textContent=state.gold}
function dialogue(lines,done){let i=0;$('#dialogue').classList.remove('hidden');const render=()=>{$('#speaker').textContent=lines[i][0];$('#dialogue-text').textContent=lines[i][1];};render();$('#dialogue-next').onclick=()=>{beep(520);i++;if(i>=lines.length){$('#dialogue').classList.add('hidden');done&&done()}else render()}}
function choices(arr){const p=$('#choice-panel');p.innerHTML='';p.classList.remove('hidden');arr.forEach(c=>{const b=document.createElement('button');b.textContent=c.text;b.onclick=()=>{p.classList.add('hidden');c.fn()};p.appendChild(b)})}
function startLevel(){const l=locations[state.level-1];dialogue([['LYRA',state.level===1?'The first Dawn Shard sleeps beneath the vale.':'The next chapter of Anoria is waiting.'],['ARIA',`I will finish the quest: ${l.quest}.`]],()=>choices([{text:'Explore the main path',fn:()=>state.level===5?startBoss():startEncounter()},{text:'Speak with an ally',fn:()=>talk(l.npc[0])},{text:'Open the world map',fn:map}]));}
function talk(name){const n=npcs[name];dialogue([[name,n.bio],['ARIA',`I need your help in ${locations[state.level-1].name}.`],[name,state.level===5?'Then stand with us for the final dawn.':'Take this advice: trust your instincts.']],()=>{state.gold+=10;state.questDone++;burst(10);save();updateHud()})}
function startEncounter(){const l=locations[state.level-1];if(Math.random()<.65)return startCombat(l.enemy,state.level===5);rewardQuest()}
function rewardQuest(){state.xp+=45;state.gold+=25;state.shards+=1;state.questDone++;state.mana=Math.min(state.maxMana,state.mana+20);save();burst(30);dialogue([['NARRATOR','Quest complete. A Dawn Shard answers your call.'],['ARIA','One step closer to the restored sky.']],()=>advance())}
function startCombat(enemyName,boss=false){state.combat=true;state.guard=false;state.enemy={name:enemyName,max:boss?260:80,hp:boss?260:80,power:boss?24:12,boss,phase:1};$('#enemy-name').textContent=enemyName;$('#enemy-hp').style.width='100%';$('#combat-hud').classList.remove('hidden');$('#enemy').classList.remove('hidden');$('#enemy').classList.toggle('boss',boss);dialogue([[enemyName,boss?'The Night King bends time itself. Prepare.':'A creature of shadow blocks your path.']],()=>{$('#dialogue').classList.add('hidden')})}
function ability(kind){if(!state.combat||state.paused)return;const cost={slash:0,arcane:15,guard:8,heal:20}[kind];if(state.mana<cost){beep(120);return}state.mana-=cost;let damage=0;if(kind==='slash')damage=weapons[state.weapon].power+Math.floor(Math.random()*9);if(kind==='arcane')damage=32+Math.floor(Math.random()*12);if(kind==='guard'){state.guard=true;damage=8}if(kind==='heal'){state.hp=Math.min(state.maxHp,state.hp+34);burst(18)}state.enemy.hp=Math.max(0,state.enemy.hp-damage);if(damage)burst(8);$('#enemy-hp').style.width=(state.enemy.hp/state.enemy.max*100)+'%';updateHud();beep(kind==='guard'?260:kind==='heal'?680:440,.13,kind==='arcane'?'triangle':'square');if(state.enemy.hp<=0)return winCombat();setTimeout(enemyTurn,280)}
function enemyTurn(){if(!state.combat)return;let damage=state.enemy.power+Math.floor(Math.random()*8);if(state.guard){damage=Math.ceil(damage*.35);state.guard=false}state.hp=Math.max(1,state.hp-damage);updateHud();$('#player').classList.add('hit');setTimeout(()=>$('#player').classList.remove('hit'),260);if(state.enemy.boss&&state.enemy.hp<state.enemy.max*.67&&state.enemy.phase===1){state.enemy.phase=2;bossPhase(2)}else if(state.enemy.boss&&state.enemy.hp<state.enemy.max*.34&&state.enemy.phase===2){state.enemy.phase=3;bossPhase(3)}if(state.hp<=1){state.hp=100;state.mana=state.maxMana;dialogue([['LYRA','The Dawn Shard revives you. Do not surrender.']],()=>{});burst(35)}updateHud()}
function bossPhase(p){burst(50);dialogue([['NIGHT KING',p===2?'Nightfall! The citadel awakens.':'Enough! I will shatter the stars.'],['ARIA',`Phase ${p}: I am still standing.`]],()=>{})}
function winCombat(){const boss=state.enemy.boss;state.combat=false;$('#combat-hud').classList.add('hidden');$('#enemy').classList.add('hidden');state.xp+=boss?180:65;state.gold+=boss?200:35;state.shards+=boss?2:1;state.questDone++;save();burst(60);dialogue([[state.enemy.name,'Your light… has defeated the darkness.'],['ARIA',boss?'Anoria will see another dawn.':'The path is clear.']],()=>boss?ending():advance())}
function advance(){if(state.level<locations.length){state.level++;state.hp=Math.min(state.maxHp,state.hp+30);state.mana=state.maxMana;save();renderLevel();setTimeout(startLevel,500)}else ending()}
function startBoss(){startCombat('NIGHT KING',true)}
function ending(){state.level=5;save();dialogue([['LYRA','Look! The stars are moving again.'],['TORREN','The realm is free.'],['NYX','And the next adventure is calling.'],['NARRATOR','ANORIA — DAWN RESTORED.']],()=>openModal(`<h2>🌅 Dawn Restored</h2><p>You completed the 2026 RPG campaign prototype.</p><p>XP <b>${state.xp}</b> · Gold <b>${state.gold}</b> · Shards <b>${state.shards}</b></p><button class="primary" onclick="closeModal()">Continue Exploring</button>`))}
function inventory(){openModal(`<h2>🎒 Arsenal & Inventory</h2><div class="inventory-grid">${state.inventory.map(i=>`<div class="item">✨<br>${i}</div>`).join('')}<div class="item">⚔️<br>${state.weapon}<small>${weapons[state.weapon].rarity}</small></div><div class="item">💎<br>${state.shards} Shards</div><div class="item">🪙<br>${state.gold} Gold</div><div class="item">⭐<br>${state.xp} XP</div></div><h3>Weapons</h3><div class="weapon-list">${Object.keys(weapons).map(w=>`<button class="${state.weapon===w?'selected':''}" onclick="equip('${w}')">⚔️ ${w}<small>${weapons[w].rarity} · Power ${weapons[w].power}</small></button>`).join('')}</div>`)}
function equip(w){state.weapon=w;save();inventory();beep(700)}
function map(){openModal(`<h2>🗺 World Map</h2><div class="world-map">${locations.map((l,i)=>`<div class="map-node ${i===state.level-1?'current':''} ${i<state.level-1?'done':''}"><span>${i+1}</span><b>${l.name}</b><small>Chapter ${l.chapter}</small></div>`).join('')}</div>`)}
function quests(){openModal(`<h2>📜 Quest Log</h2><div class="quest-list">${locations.map((l,i)=>`<article class="${i===state.level-1?'active':''}"><b>${i<state.level-1?'✓':'◈'} ${l.quest}</b><p>${l.detail}</p></article>`).join('')}</div>`)}
function journal(){openModal(`<h2>📖 Chronicle of Anoria</h2><p><b>Prophecy:</b> Five Dawn Shards can restart the frozen sky.</p><p><b>Allies:</b> Lyra, Torren, Nyx.</p><p><b>Campaign:</b> Chapter ${locations[state.level-1].chapter} — ${locations[state.level-1].name}</p><p><b>Progress:</b> ${state.shards} shards · ${state.questDone} quests</p>`)}
function settings(){openModal(`<h2>⚙️ Settings</h2><label class="setting"><span>Sound effects</span><input id="set-sound" type="checkbox" ${state.sound?'checked':''}></label><label class="setting"><span>Music</span><input id="set-music" type="checkbox" ${state.music?'checked':''}></label><label class="setting"><span>Volume</span><input id="set-volume" type="range" min="0" max="1" step=".05" value="${state.volume}"></label><button class="secondary" onclick="installPWA()">📲 Install ANORIA</button><button class="secondary" onclick="resetGame()">Reset Save</button>`);$('#set-sound').onchange=e=>state.sound=e.target.checked;$('#set-music').onchange=e=>{state.music=e.target.checked;if(state.music)startMusic()};$('#set-volume').oninput=e=>state.volume=+e.target.value;}
function resetGame(){localStorage.removeItem(SAVE_KEY);location.reload()}
function openModal(html){$('#modal-content').innerHTML=html;$('#overlay').classList.remove('hidden')}function closeModal(){$('#overlay').classList.add('hidden')}
function how(){openModal('<h2>How to Play</h2><p>Explore the five regions, meet allies, complete quests, collect shards and defeat the Night King.</p><ul><li>Move with the D-pad or arrow keys.</li><li>Interact starts exploration.</li><li>In combat, use four abilities.</li><li>Guard reduces the next hit; Moon Heal restores HP.</li><li>Your progress saves automatically.</li></ul>')}
function movePlayer(dx,dy){state.position.x=Math.max(8,Math.min(92,state.position.x+dx));state.position.y=Math.max(25,Math.min(82,state.position.y+dy));const p=$('#player');p.style.left=state.position.x+'%';p.style.bottom=state.position.y+'%';p.classList.remove('walk');void p.offsetWidth;p.classList.add('walk');beep(180,.05,'triangle')}
function burst(n=15){const s=$('#scene');for(let i=0;i<n;i++){const p=document.createElement('i');p.className='particle';p.style.left=Math.random()*100+'%';p.style.top=(20+Math.random()*70)+'%';p.style.setProperty('--dx',(Math.random()*120-60)+'px');p.style.setProperty('--dy',(Math.random()*120-60)+'px');s.appendChild(p);setTimeout(()=>p.remove(),900)}}
let audioCtx,musicTimer;function beep(freq=440,dur=.1,type='sine'){if(!state.sound)return;audioCtx??=new(window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(.035*state.volume,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+dur);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+dur)}
function startMusic(){if(musicTimer||!state.music)return;const notes=[196,247,294,247,220,262,330,262];let i=0;musicTimer=setInterval(()=>{if(state.music&&!state.paused)beep(notes[i++%notes.length],.32,'sine')},520)}
let deferredPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e});async function installPWA(){if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null}else openModal('<h2>📲 Install ANORIA</h2><p>On Android Chrome, open the browser menu and choose <b>Install app</b> or <b>Add to Home screen</b>.</p>')}
$('#start-btn').onclick=()=>{Object.assign(state,{level:1,hp:100,mana:60,gold:80,xp:0,shards:0,inventory:['Moonleaf Potion','Dawn Fragment'],weapon:'Dawnblade',questDone:0});showGame();renderLevel();save();startMusic();setTimeout(startLevel,350)};$('#continue-btn').onclick=()=>{load();startMusic();setTimeout(startLevel,250)};$('#how-btn').onclick=how;$('#settings-title').onclick=settings;$('#close-modal').onclick=closeModal;$('#overlay').onclick=e=>{if(e.target.id==='overlay')closeModal()};$('#inventory-btn').onclick=inventory;$('#map-btn').onclick=map;$('#quest-btn').onclick=quests;$('#journal-btn').onclick=journal;$('#settings-btn').onclick=settings;$('#interact-btn').onclick=()=>{if(!state.combat)startLevel()};$('#sound-btn').onclick=()=>{state.sound=!state.sound;$('#sound-btn').textContent=state.sound?'🔊':'🔇';beep(500)};$('#pause-btn').onclick=()=>{state.paused=!state.paused;openModal(`<h2>${state.paused?'⏸ Paused':'▶ Resumed'}</h2><p>Your progress is safe.</p>`)};$$('[data-ability]').forEach(b=>b.onclick=()=>ability(b.dataset.ability));$$('[data-move]').forEach(b=>b.onclick=()=>{const m=b.dataset.move;movePlayer(m==='left'?-5:m==='right'?5:0,m==='up'?4:m==='down'?-4:0)});document.addEventListener('keydown',e=>{if(e.key==='Enter')$('#interact-btn').click();if(e.key==='ArrowLeft')movePlayer(-5,0);if(e.key==='ArrowRight')movePlayer(5,0);if(e.key==='ArrowUp')movePlayer(0,4);if(e.key==='ArrowDown')movePlayer(0,-4)});if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));updateContinue();
